name: build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: 
      - develop

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: npm run make
        env:
          ARCH: ${{ matrix.arch }} 

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: out/

  notarize:
    runs-on: ${{ matrix.os }}
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with: 
          path: out/

      - name: Notarize the app
        run: |
          xcrun altool --notarize-app \
            --primary-bundle-id "com.charistheo.chromelauncher" \
            --username "${{ secrets.APPLE_ID }}" \
            --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
            --team-id "${{ secrets.APPLE_TEAM_ID }}" \
            --file "out/**/make/*.dmg" 

      - name: Staple the notarization ticket
        run: |
          xcrun stapler staple "out/**/make/*.dmg"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: out/

  release:
    runs-on: ubuntu-latest
    needs: notarize
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with: 
          path: artifacts

      - name: Zip folders
        run: |
          zip -jr macOS-ARM.zip artifacts/macos-latest-arm64/make/*
          zip -jr macOS-Intel.zip artifacts/macos-latest-x64/make/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            macOS-ARM.zip
            macOS-Intel.zip