name: build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: 
      - develop

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APPLE_APPLICATION_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_ID_APPLICATION_CERTIFICATE }}
  APPLE_INSTALLER_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_ID_INSTALLER_CERTIFICATE }}
  APPLE_APPLICATION_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_APPLICATION_CERTIFICATE_PASSWORD }}
  APPLE_INSTALLER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_INSTALLER_CERTIFICATE_PASSWORD }}
  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]

    steps:
      - name: Import Apple Developer Certificate
        run: |
          echo $APPLE_APPLICATION_CERTIFICATE | base64 --decode > application_certificate.p12
          echo $APPLE_INSTALLER_CERTIFICATE | base64 --decode > installer_certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import application_certificate.p12 -k build.keychain -P "$APPLE_APPLICATION_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security import installer_certificate.p12 -k build.keychain -P "$APPLE_INSTALLER_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          security find-identity -v -p codesigning build.keychain

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: npm run make
        env:
          ARCH: ${{ matrix.arch }} 

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: out/

  notarize:
    runs-on: ${{ matrix.os }}
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Notarize the app
        run: |
          xcrun altool --notarize-app \
            --primary-bundle-id "com.charistheo.chromelauncher" \
            --username "${{ secrets.APPLE_ID }}" \
            --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
            --team-id "${{ secrets.APPLE_TEAM_ID }}" \
            --file "out/${{ matrix.os }}-${{ matrix.arch }}/make/*.dmg" 

      - name: Staple the notarization ticket
        run: |
          xcrun stapler staple "out/${{ matrix.os }}-${{ matrix.arch }}/make/*.dmg"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./

  release:
    runs-on: ubuntu-latest
    needs: notarize
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with: 
          path: artifacts

      - name: Zip folders
        run: |
          zip -jr macOS-ARM.zip artifacts/macos-latest-arm64/make/*
          zip -jr macOS-Intel.zip artifacts/macos-latest-x64/make/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            macOS-ARM.zip
            macOS-Intel.zip