name: Build Electron App

on:
  push:
    branches:
      - main
      - test-github-action
  pull_request:
    branches: 
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: npm run make
        env:
          ARCH: ${{ matrix.arch }} 

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: out/

  release:
    needs: build
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}