name: notarize

on:
  workflow_run:
    workflows: [build]
    types:
      - completed
    # branches:
      # - main

jobs:
  notarize:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-x64-app 

      - name: Notarize the app
        run: |
          xcrun altool --notarize-app \
            --primary-bundle-id "com.charistheo.chromelauncher" \
            --username "${{ secrets.APPLE_ID }}" \
            --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
            --team-id "${{ secrets.APPLE_TEAM_ID }}" \
            --file "out/**/make/*.dmg" 

      - name: Staple the notarization ticket
        run: |
          xcrun stapler staple "out/**/make/*.dmg"