name: release

permissions:
  contents: write

on:
  workflow_run:
    # TODO update to 'notarize'
    workflows: [build]
    types: [completed]
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v1